import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import { QueryProvider } from "@/lib/QueryProvider";
import DynamicFooterAndNavBar from "@/components/DynamicFooterAndNavBar";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",

})


export const metadata: Metadata = {
  title: "SkillShare Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <QueryProvider>
          <StoreProvider>
            <Toaster />
            <DynamicFooterAndNavBar>
              {children}
              <Toaster />
            </DynamicFooterAndNavBar>
          </StoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
